### ISSUE TITLE
Wi-Fi not working

### ISSUE THREAD

**Issue by AnakTeka** [qiqco/Dell-inspiron-13-7370-Hackintosh#1]
Hi, many thanks for the EFI folder, I have successfully installed Big Sur 11.2.3 with your config on Dell Inspiron 7370. But unfortunately the Wi-Fi is not working, do I have to do something for the Wi-Fi card?

Thanks.

**Comment by qiqco** [comment]
What is your Wi-Fi model?

**Comment by AnakTeka** [comment]
Thanks for the response, turned out because I'm using BigSur, I had to replace AirportItlwm.kext with BigSur's version, and Wi-Fi works afterwards!

Btw when I play sound from HDMI or sound from audio jack the audio shuttering/flickering every like 10 seconds, do you also have this issue?

**Comment by qiqco** [comment]
I don't know about HDMI, but my headphone jack is OK. Do you use the combojack I provided to repair it

**Comment by qiqco** [comment]
你所描述的两个我都是正常

**Comment by AnakTeka** [comment]
> I don't know about HDMI, but my headphone jack is OK. Do you use the combojack I provided to repair it

I did run the combojack install script that you provide but the problem still there. The headphone jack is working (has sound output from the headset) but every like 10 seconds when I play sound from YouTube or Spotify the sound stutters a bit (few ms seconds I think, at least I can notice the stutters ) but after the stutters it will sound perfectly, and this will happen repeatedly. I have updated to Monterey but the problem persist, wondering is this also happen to you?

**Comment by qiqco** [comment]
> 我并没有测试过，我待会儿会对此问题进行测试

**Comment by AnakTeka** [comment]
Thanks, appreciate it! I have also installed the newest released package and now my brightness key works flawlessly!

**Comment by qiqco** [comment]
刚刚我进行了测试，耳机接口确实存在问题，我会尽量修复他的
